#!/bin/sh

: "${USER_ID:=$(stat -c%u .)}"
: "${GROUP_ID:=$(stat -c%g .)}"
: "${GROUP_NAME:=${USER_NAME:=dobe}}"

groupadd -g "$GROUP_ID" "$GROUP_NAME" || exit
useradd -lmg "$GROUP_NAME" -u "$USER_ID" "$USER_NAME" || exit

execGosu() { exec gosu "$USER_NAME" "$@"; }

if [ "$(command -v "$1")" ]; then
	execGosu "$@"
elif [ $# -eq 1 ]; then
	execGosu sh -c "$1"
else
	echo "$@" | execGosu sh -s
fi
