#!/bin/sh

## This Source Code Form is subject to the terms of the Mozilla Public
## License, v. 2.0. If a copy of the MPL was not distributed with this
## file, You can obtain one at https://mozilla.org/MPL/2.0/.

: "${USER_ID:=$(stat -c%u .)}"
: "${GROUP_ID:=$(stat -c%g .)}"
: "${GROUP_NAME:=${USER_NAME:=dobe}}"

groupadd -g "$GROUP_ID" "$GROUP_NAME" || exit
useradd -lmg "$GROUP_NAME" -u "$USER_ID" "$USER_NAME" || exit
ln -s /home/dobe.ssh "/home/${USER_NAME}/.ssh"

execGosu() { exec gosu "$USER_NAME" "$@"; }

if [ "$(command -v "$1")" ]; then
	execGosu "$@"
elif [ $# -eq 1 ]; then
	execGosu sh -c "$1"
else
	echo "$@" | execGosu sh -s
fi
