#!/bin/sh

## This Source Code Form is subject to the terms of the Mozilla Public
## License, v. 2.0. If a copy of the MPL was not distributed with this
## file, You can obtain one at https://mozilla.org/MPL/2.0/.

jobsDefault=$(($(getconf _NPROCESSORS_ONLN) - 1))
[ "$jobsDefault" -lt 1 ] && jobsDefault=1

: "${IOCLASS:=3}"
: "${IOLEVEL:=7}"
: "${NICE:=19}"
: "${JOBS=$jobsDefault}"

ioLevelParam=$([ "$IOCLASS" -ne 3 ] && echo -n"$IOLEVEL")

ionice -c"$IOCLASS" $ioLevelParam \
	nice -n"$NICE" \
	make -j"$JOBS" "$@"
